<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>re</string>
	</array>
	<key>name</key>
	<string>ReVIEW</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Patagraph = </string>
			<key>match</key>
			<string>(^={1,4}(\{([^\}]+)\})?)\s(.*)</string>
			<key>name</key>
			<string>patagraph.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Column ===[column]</string>
			<key>match</key>
			<string>(^={3}\[(column)\])\s(.*)</string>
			<key>name</key>
			<string>column.review.begin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Column ===[/column]</string>
			<key>match</key>
			<string>(^={3}\[/(column)\])</string>
			<key>name</key>
			<string>column.review.end</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Bullet point * </string>
			<key>match</key>
			<string>^\s+\*+ </string>
			<key>name</key>
			<string>keyword.review</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric bullet point like 1. </string>
			<key>match</key>
			<string>^\s+[0-9]+\. </string>
			<key>name</key>
			<string>keyword.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Definition list like : Alpha </string>
			<key>match</key>
			<string>^\s*(:)\s(.*)</string>
			<key>name</key>
			<string>definition.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(list)\[([^\]]*)\]\[((\\]|[^]])*)\](\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>List //list[main][main()]{ ... //}</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>list.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(emlist)(\[((\\]|[^]])*)\])?(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>EMList //emlist[main()]{ ... //}</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>emlist.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(source)\[([^\]]*)\](\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>//source[...]{ ... //}</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(listnum)\[([^\]]*)\]\[((\\]|[^]])*)\](\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>//listnum[hello][...]</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>listnum.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>@&lt;list&gt;{hello} </string>
			<key>match</key>
			<string>(@&lt;)(list)(&gt;\{)([^\}]*)(\})</string>
			<key>name</key>
			<string>listnum.inline.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(image)\[([^\]]*)\](\[([^\]]*)\])?\[((\\]|[^]])*)\](\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Image //image[unixhistory][...][scale=2]</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>image.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>@&lt;img&gt;{unixhistory} </string>
			<key>match</key>
			<string>(@&lt;)(img)(&gt;\{)([^\}]*)(\})</string>
			<key>name</key>
			<string>image.inline.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>//indepimage[sin_x][caption]</string>
			<key>match</key>
			<string>^(//)(indepimage)\[([^\]]*)\](\[([^\]]*)\])?</string>
			<key>name</key>
			<string>indepimage.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(graph)\[([^\]]*)\]\[(graphviz|gnuplot|blockdiag|aafigure)\](\[((\\]|[^]])*)\])?(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Graph //graph[sin_x][gnuplot][caption]{ ... //}</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>graph.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(table)\[([^\]]*)\]\[((\\]|[^]])*)\](\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Table //table[envvars][...]</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>table.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>@&lt;table&gt;{envvars} </string>
			<key>match</key>
			<string>(@&lt;)(table)(&gt;\{)([^\}]*)(\})</string>
			<key>name</key>
			<string>table.inline.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(footnote)\[([^\]]*)\]\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Footnote //footnote[site][...]</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>footnote.review</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>@&lt;fn&gt;{site} </string>
			<key>match</key>
			<string>(@&lt;)(fn)(&gt;\{)([^\}]*)(\})</string>
			<key>name</key>
			<string>footnote.inline.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)(bibpaper)\[([^\]]*)\]\[((\\]|[^]])*)\](\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Bib //bibpaper[lins][Lins, 1991]{ ... //}</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>bibpaper.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>//noindent</string>
			<key>match</key>
			<string>^(//)(noindent)</string>
			<key>name</key>
			<string>noindent.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>//raw[...]</string>
			<key>match</key>
			<string>^(//)(raw)\[([^\]]*)\]</string>
			<key>name</key>
			<string>raw.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(//)([^\{\[\]]+)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>//hoge{ ... //}</string>
			<key>end</key>
			<string>(^//\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>block.review</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment #@# </string>
			<key>match</key>
			<string>#@#.*</string>
			<key>name</key>
			<string>comment.line.review</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Warning #@warn(...) </string>
			<key>match</key>
			<string>#@warn\(.*\)</string>
			<key>name</key>
			<string>comment.review</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comment @&lt;comment&gt;{...} //comment{...} </string>
			<key>match</key>
			<string>(@&lt;comment&gt;|//comment)\{.*\}</string>
			<key>name</key>
			<string>comment.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#@require, #@provide</string>
			<key>match</key>
			<string>^(#@(require)|#@(provide))</string>
			<key>name</key>
			<string>require.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(#@(mapfile)|#@(mapoutput))\(([^\)]*)\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#@mapfile(...) ... #@end</string>
			<key>end</key>
			<string>^(#@)(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>mapfile.review</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(#@)(maprange)\(([^,]*,[^\)]*)\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#@maprange(..., ...) ... #@end</string>
			<key>end</key>
			<string>^(#@)(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
			</dict>
			<key>name</key>
			<string>maprange.review</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.review</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.review</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.review</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline instruction like @&lt;list&gt;{program} </string>
			<key>match</key>
			<string>(@&lt;)([a-z]+)(&gt;\{)((\\}|[^}])*)(\})</string>
			<key>name</key>
			<string>instruction.inline.review</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.review</string>
	<key>uuid</key>
	<string>5fa7fee2-7333-4924-a208-ab04d0a64748</string>
</dict>
</plist>
